# Manually set session timeout to 5 minutes
# @see https://github.com/peholmst/vaadin4spring/issues/51
server:
    sessionTimeout: 300
    
# Servlet mapping for VaadinServlet
vaadin:
    servlet:
        urlMapping: /*
        params:
            productionMode: true
            
# Servlet init params for StaticContentServlet
    static:
        servlet:
            params:
                widgetset: common.MyAppWidgetset.gwt.xml